name: Microservices Trigger CI

on:
  push:
    branches: [ main ]
    

permissions:
  contents: read
  packages: write

jobs:
  # -------------------------------
  # Job 1: Detect changed services
  # -------------------------------
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.changed.outputs.services }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect changed services
        id: changed
        shell: bash
        run: |
          SERVICES=$(find src -mindepth 1 -maxdepth 1 -type d -printf '%f\n' \
            | sort \
            | jq -R -s -c 'split("\n") | map(select(length > 0))')

          echo "Services to build: $SERVICES"
          echo "services=$SERVICES" >> "$GITHUB_OUTPUT"


  # --------------------------------------------------
  # Job 2: Call reusable workflow (matrix per service)
  # --------------------------------------------------
  build-and-push:
    needs: detect-changes
    if: needs.detect-changes.outputs.services != '[]'

    strategy:
      fail-fast: false
      matrix:
        service: ${{ fromJson(needs.detect-changes.outputs.services) }}

    # 🚨 IMPORTANT:
    # Reusable workflows are called at JOB level
    uses: ./.github/workflows/microservice-ci.yaml

    with:
      service: ${{ matrix.service }}
